Sermon Series Devotionals Wild Conversations, Week 2
flatlandchurch/flatland-site-hugo pull request #29
Opened 2021-04-24 01:06 UTC by wereveal

2021-04-24 03:16 UTC, Renddslow requested changes
Looks like one of the files got jenky again

2021-04-25 15:01 UTC, wereveal commented
What? You don't like improper file encodings?  🙂 Fixed. It is a Word to text encoding mess up. Working out an export script to make sure it is exported correctly from now on.

2021-05-04 15:32 UTC, wereveal commented
have added week 3 to the fixed week 2 commit.

2021-05-05 00:20 UTC, Renddslow approved these changes

2021-05-05 00:20 UTC, merged